# -*- coding: utf-8 -*-
"""01_SVM_Classification_example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_upyWjFu1rSUwJOiBZLH6Q4D5VkvP7Jk
"""

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

# 1. Load the dataset
iris = datasets.load_iris()
X = iris.data  # Features: Sepal length, Sepal width, Petal length, Petal width
y = iris.target # Labels: 0 (Setosa), 1 (Versicolor), 2 (Virginica)

# 2. Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# 3. Feature Scaling (Crucial for SVM!)
# SVM calculates distances, so all features must be on the same scale
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# 4. Initialize and Train the SVM
# We use a Linear kernel here for simplicity
model = SVC(kernel='linear', C=1.0) # C is given before and hence this model hyperparameter
model.fit(X_train, y_train) # Model gets trained

# 5. Make Predictions
y_pred = model.predict(X_test)

# 6. Evaluate
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

"""Images - we need construct it as an array (Ex : PIL - pillow library)
SVM cannot load the images directly
Images --> converted to features and then feed the features in to the library (features should be of numbers - machine learning algorithm will not learn)

1 - record1 - 8 * 8 array (digit) - image </br>
2 - record2 - 8 * 8 array (digit) - image </br>

0 21 31 0 0 0 0  ......... 255
"""

digits = datasets.load_digits()

# 2. Reshape and Prepare Data
# Each image is 8x8, we flatten it into a 1D array of 64 pixels
n_samples = len(digits.images)
data = digits.images.reshape((n_samples, -1))

data

import matplotlib.pyplot as plt
from sklearn import datasets, svm, metrics
from sklearn.model_selection import train_test_split

# 1. Load the digits dataset
digits = datasets.load_digits()

# 2. Reshape and Prepare Data
# Each image is 8x8, we flatten it into a 1D array of 64 pixels
n_samples = len(digits.images)
data = digits.images.reshape((n_samples, -1))

# 3. Split: 50% training, 50% testing
X_train, X_test, y_train, y_test = train_test_split(
    data, digits.target, test_size=0.5, shuffle=False
)

# 4. Create and Train the SVM Classifier
# If gamma is large, the value of the kernel drops to zero very quickly as points move apart.
# This means the SVM "forgets" about distant points almost immediately.
# If gamma is small, the value drops slowly, meaning distant points still carry significant weight in the calculation.
# We use 'gamma', which defines how far the influence of a single example reaches
clf = svm.SVC(gamma=0.001, C=100) # RBF model is fit
clf.fit(X_train, y_train)

# 5. Predict the value of the digit on the test subset
predicted = clf.predict(X_test)

# 6. Visualize the results
_, axes = plt.subplots(nrows=1, ncols=4, figsize=(10, 3))
for ax, image, prediction in zip(axes, X_test, predicted):
    ax.set_axis_off()
    image = image.reshape(8, 8)
    ax.imshow(image, cmap=plt.cm.gray_r, interpolation="nearest")
    ax.set_title(f"Pred: {prediction}")

# 1. Load Data
print("Fetching Fashion-MNIST...")
fashion = fetch_openml('Fashion-MNIST', version=1, as_frame=False)
X, y = fashion.data, fashion.target.astype(int)
print(X)
print(y)

print(X.shape)
print(X[0])

from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load Data
print("Fetching Fashion-MNIST...")
fashion = fetch_openml('Fashion-MNIST', version=1, as_frame=False)
X, y = fashion.data, fashion.target.astype(int)

# 2. Scale and Split
# We scale pixels to [0, 1] and take a subset (10k) for demonstration speed
X = X / 255.0
X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=10000, test_size=2000, random_state=42, stratify=y
)

# 3. Create a Pipeline
# PCA reduces 784 pixels to the 50 most important "components"
# SVC with RBF kernel handles the complex shapes of clothing
clf = make_pipeline(
    PCA(n_components=50, whiten=True),
    SVC(kernel='rbf', C=5, gamma='auto')
)

# 4. Train
print("Training SVM...")
clf.fit(X_train, y_train)

# 5. Predict and Evaluate
y_pred = clf.predict(X_test)
print(f"Accuracy: {clf.score(X_test, y_test):.2%}") # This steps performs these steps here - predict, compare and calculate

# Label names for the 10 categories
target_names = ['T-shirt', 'Trouser', 'Pullover', 'Dress', 'Coat',
                'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

plt.figure(figsize=(10,8))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', xticklabels=target_names, yticklabels=target_names)
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.title('Fashion SVM Confusion Matrix')
plt.show()

"""We use face recgnition from the kaggle dataset :

**Labelled Faces in the Wild (LFW) Dataset** </br>

kaggle URL : https://www.kaggle.com/datasets/jessicali9530/lfw-dataset/data

**Support Vector Machines (SVM)** </br>
**Use the "Labeled Faces in the Wild" (LFW) dataset**
"""

import matplotlib.pyplot as plt
from sklearn.datasets import fetch_lfw_people

# Load the dataset
faces = fetch_lfw_people(min_faces_per_person=70, resize=0.4)

# Plot the first 10 faces
fig, axes = plt.subplots(2, 5, figsize=(15, 8),
                         subplot_kw={'xticks':[], 'yticks':[]})

for i, ax in enumerate(axes.flat):
    ax.imshow(faces.images[i], cmap='bone')
    ax.set_title(faces.target_names[faces.target[i]])

plt.suptitle("Sample Images from the LFW Dataset", fontsize=16)
plt.show()

from sklearn.datasets import fetch_lfw_people
faces = fetch_lfw_people(min_faces_per_person=60)
print(faces.target_names)
print(faces.images.shape)

# The shape of one image (e.g., 50 pixels high by 37 pixels wide)
print(f"Image Dimensions: {faces.images[0].shape}")

# The raw pixel values of the first row of the first image
print("\nFirst row of pixel intensities (0-255):")
print(faces.images[0][0])

"""Reshaping for the SVM

SVMs cannot process a 2D square image directly; they require a "flat" 1D vector.

    If an image is 50×37 pixels, the SVM sees it as a single long row of 1,850 numbers.

    The Data: X=[pixel1​,pixel2​,...,pixel1850​]

Summary of "What the Data Is":

    Visual: A human face (e.g., George W. Bush).

    Mathematical: A 2D matrix of light intensities.

    Input for SVM: A flattened 1D vector of those intensities, which will later be reduced by PCA to find the most important "features" or facial landmarks.

## Biometric Authentication: The Business Problem

### **High-Security Enterprise Challenge**

**A high-security enterprise requires:**
- Non-intrusive biometric authentication
- Access to restricted physical areas
- Secure digital assets
- Real-time performance (<100ms)


---

### **Environmental Challenges**

| **Condition** | **Technical Difficulty** | **Impact** |
|---------------|--------------------------|------------|
| **Varying lighting** | Shadows, glare, low-light | Feature extraction failure |
| **Facial expressions** | Smiles, frowns, talking | Intra-class variability |
| **Real-time constraint** | <100ms inference | Deployment feasibility |

---

### **Critical Error Trade-offs**

❌ FALSE NEGATIVE (Type II Error)
→ Legitimate user → DENIED access
→ Operational friction
→ Productivity loss
→ User frustration

✅ AUTHORIZED PERSONNEL → ACCESS GRANTED ✅

❌ FALSE POSITIVE (Type I Error)
→ Intruder → GRANTED access
→ CRITICAL SECURITY BREACH
→ Physical/digital compromise
→ Legal/regulatory disaster ⚖️


---

### **Business Impact Quantification**

| **Metric** | **Target** | **Consequence of Failure** |
|------------|------------|----------------------------|
| **False Positive Rate** | **<0.01%** | Security breach 🚨 |
| **False Negative Rate** | **<1%** | User friction 😤 |
| **Latency** | **<100ms** | System unusable |
| **Accuracy** | **>99.5%** | Regulatory compliance |

---

### **Why ML is Essential**
ML Solution delivers:

    Adaptive decision boundaries

    Real-time anomaly detection

    Robust to environmental variance

    One-Class SVM / Autoencoder ready

Deep learning methods do this more effectively as compared to the SVM methods

## Facial Recognition Pipeline: Problem Objective

### **Core Mission**
**Build a robust facial recognition pipeline that classifies input images into known identities.**

---

### **Specific Technical Goals**

| **Goal** | **Technique** | **Why Critical** |
|----------|---------------|------------------|
| **Dimensionality Reduction** | **PCA (Eigenfaces)** | 1000s → 100s features<br>Computational efficiency |
| **Optimal Separation** | **SVM + RBF Kernel** | Non-linear decision boundaries |
| **High Performance** | **F1-Score Optimization** | Balanced Precision/Recall<br>Especially for rare classes |

---

**Step 1: Data Collection & Loading**

We use the `fetch_lfw_people` dataset, which consists of thousands of collated photos of public figures.
"""

from time import time

import matplotlib.pyplot as plt
from scipy.stats import loguniform

from sklearn.datasets import fetch_lfw_people
from sklearn.decomposition import PCA
from sklearn.metrics import ConfusionMatrixDisplay, classification_report
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

lfw_people

lfw_people.images.shape

50*37

print(lfw_people.target_names)
print(lfw_people.target)

lfw_people = fetch_lfw_people(min_faces_per_person=70, resize=0.4)

# introspect the images arrays to find the shapes (for plotting)
n_samples, h, w = lfw_people.images.shape

# for machine learning we use the 2 data directly (as relative pixel
# positions info is ignored by this model)
X = lfw_people.data
n_features = X.shape[1]

# the label to predict is the id of the person
y = lfw_people.target
target_names = lfw_people.target_names
n_classes = target_names.shape[0]

print("Total dataset size:")
print("n_samples: %d" % n_samples)
print("n_features: %d" % n_features)
print("n_classes: %d" % n_classes)

"""**Step 2: Split the data set and perform Feature Engineering (PCA)**

Raw pixel data is too "noisy" for SVM. PCA reduces the features from ~1800 pixels down to ~150 principal components that represent the "essence" of the face.
"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Compute a PCA (eigenfaces) on the face dataset (treated as unlabeled dataset): unsupervised feature extraction / dimensionality reduction

n_components = 150

print("Extracting the top %d eigenfaces from %d faces" % (n_components, X_train.shape[0]))
t0 = time()
pca = PCA(n_components=n_components, svd_solver="randomized", whiten=True).fit(X_train)
print("done in %0.3fs" % (time() - t0))

eigenfaces = pca.components_.reshape((n_components, h, w))

print("Projecting the input data on the eigenfaces orthonormal basis")
t0 = time()
X_train_pca = pca.transform(X_train)
X_test_pca = pca.transform(X_test)
print("done in %0.3fs" % (time() - t0))

"""**Step 3 : Train an SVM classification model**

"""

print("Fitting the classifier to the training set")
t0 = time()
param_grid = {
    "C": loguniform(1e3, 1e5), # Regularization
    "gamma": loguniform(1e-4, 1e-1), # Gamma/Kernel Width
}
clf = RandomizedSearchCV(SVC(kernel="rbf", class_weight="balanced"), param_grid, n_iter=10)
clf = clf.fit(X_train_pca, y_train)
print("done in %0.3fs" % (time() - t0))
print("Best estimator found by grid search:")
print(clf.best_estimator_)

"""**Step 4 : Predicting the results**"""

print("Predicting people's names on the test set")
t0 = time()
y_pred = clf.predict(X_test_pca)
print("done in %0.3fs" % (time() - t0))

print(classification_report(y_test, y_pred, target_names=target_names))
ConfusionMatrixDisplay.from_estimator(clf, X_test_pca, y_test, display_labels=target_names, xticks_rotation="vertical")
plt.tight_layout()
plt.show()

def plot_gallery(images, titles, h, w, n_row=3, n_col=4):
    """Helper function to plot a gallery of portraits"""
    plt.figure(figsize=(2* n_col, 3 * n_row))
    plt.subplots_adjust(bottom=0, left=0.01, right=0.99, top=0.90, hspace=0.35)
    for i in range(n_row * n_col):
        plt.subplot(n_row, n_col, i + 1)
        plt.imshow(images[i].reshape((h, w)), cmap=plt.cm.gray)
        plt.title(titles[i], size=12)
        plt.xticks(())
        plt.yticks(())

def title(y_pred, y_test, target_names, i):
    pred_name = target_names[y_pred[i]].rsplit(" ", 1)[-1]
    true_name = target_names[y_test[i]].rsplit(" ", 1)[-1]
    return "predicted: %s\ntrue:      %s" % (pred_name, true_name)


prediction_titles = [title(y_pred, y_test, target_names, i) for i in range(y_pred.shape[0])]

plot_gallery(X_test, prediction_titles, h, w)

eigenface_titles = ["eigenface %d" % i for i in range(eigenfaces.shape[0])]
plot_gallery(eigenfaces, eigenface_titles, h, w)

plt.show()

